### ISSUE TITLE
Phase 1.0 Tracking Issue

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#65]
For those who do not want to look at GitHub Projects :laughing:

These activities are taken directly from the [approved grant proposal](https://github.com/ipfs/devgrants/tree/master/open-grants/ipfs-rust).

1. Project Setup
    1. Git Repositories
        * [x] https://github.com/ipfs-rust/logo/issues/2
        * [x] https://github.com/ipfs-rust/rust-ipfs/issues/41
        * [x] https://github.com/ipfs-rust/rust-ipfs/issues/54
        * [x] https://github.com/ipfs-rust/rust-ipfs/issues/61
        * [x] https://github.com/ipfs-rust/logo/issues/2
    2. Code Organization
        * [x] Done in the HTTP Scaffolding Issue
    3. CI/CD
        * [x] https://github.com/ipfs-rust/rust-ipfs/issues/62
2. HTTP Scaffolding
    1. Simple Daemonization with `501 NOT IMPLEMENTED` boilerplate
        * [x] https://github.com/ipfs-rust/rust-ipfs/issues/60
3. Conformance Testing
    1. Update js-ipfsd-ctl
        * [x] https://github.com/ipfs-rust/npm-rust-ipfs-dep/issues/1 (potentially optional) 
    2. Update ipfs/interface-js-ipfs-core (failing tests)
        * [x] Potentially no updates required since they roll upward from `js-ipfsd-ctl
    3. Run conformance testing on implemented endpoints
4. Interoperability Testing
    1. Update ipfs/interop
        * [ ] https://github.com/ipfs-rust/interop/issues/1
    2. Interop Testing
5. Project Milestone Report https://github.com/ipfs-rust/rust-ipfs/issues/66
    * [ ] https://github.com/ipfs-rust/rust-ipfs/issues/66
    1. Executive Summary
    2. Comformance Test Results
    3. Interop Report
6. Rust IPFS Blog Post
    * [ ] https://github.com/ipfs-rust/rust-ipfs/issues/67

**Comment by aphelionz** [comment]
Not needed since the decision was made to use GH projects
